### ISSUE TITLE
Tracking v1.0.0

### ISSUE THREAD

**Issue by kum-deepak** [stomp-js/rx-stomp#251]
Finally, the library is moving towards 1.0.0 status.

Main targets:

- [x] Change license to Apache v2
- [x] Concept of `discardWebsocketOnCommFailure` (see https://github.com/stomp-js/ng2-stompjs/issues/173#issuecomment-692674836)
- [x] Update CI infrastructure - test on Edge and Safari as well.
- [x] Align with @stomp/stompjs@6

**Comment by kum-deepak** [comment]
Install `@stomp/rx-stomp@beta` (or `@stomp/ng2-stompjs@beta`) to test out `discardWebsocketOnCommFailure`. Set this flag on your config to activate it. Please report your findings. Please see https://github.com/stomp-js/stompjs/issues/247 for details.

**Comment by jbakoc1** [comment]
@kum-deepak it works as expected. 
![screen](https://user-images.githubusercontent.com/63701713/94793570-572da200-03e3-11eb-8273-b6200d9893f2.png)
Is there any info you need from me?

**Comment by kum-deepak** [comment]
This is good. Please share log statements until much further (at least a few more minutes). I specifically want to see when it connects again, and also when the original socket is actually discarded. I want to check that by mistake it does not open two connections internally. You can attach the log as a text file as well (after masking as needed).

**Comment by jbakoc1** [comment]
@kum-deepak here is the log file.
[localhost-1601709800176.log](https://github.com/stomp-js/rx-stomp/files/5321262/localhost-1601709800176.log)

**Comment by kum-deepak** [comment]
Many thanks, @jbakoc1! The log output looks perfect.

**Comment by jbakoc1** [comment]
@kum-deepak I am glad to hear that. When you expect to merge it with the master branch?

**Comment by kum-deepak** [comment]
For now, it will be available as `beta` tag. There are more breaking changes that I am going to add before releasing a 1.0.0 version.

You may choose to fix to current beta to avoid breakage due to future beta releases.

**Comment by kum-deepak** [comment]
Some of those changes will be in the underlying @stomp/stompjs library.

**Comment by kum-deepak** [comment]
Published beta4, install using:

```bash
$ npm i @stomp/rx-stomp@beta
```

**Comment by jbakoc1** [comment]
Hey @kum-deepak 
Which version you recommend to install for the production system?

**Comment by kum-deepak** [comment]
I have already released 1.0.1. You should use that in production.

**Comment by kum-deepak** [comment]
Simply install as:

```bash
$ npm i @stomp/rx-stomp
```

**Comment by jbakoc1** [comment]
Thanks. You are the best 😉

**Comment by kum-deepak** [comment]
Version 1.0.1 is relased.
